const CSV_PARSER = "CSV_PARSER"
const GHERKIN_PARSER = "GHERKIN_PARSER"
const PANDAVAREHUS_POLISER = "PANDAVAREHUS_POLISER"
const PANDAVAREHUS_TIDSLINJEHENDELSER = "PANDAVAREHUS_TIDSLINJEHENDELSER"

export {
    CSV_PARSER,
    GHERKIN_PARSER,
    PANDAVAREHUS_POLISER,
    PANDAVAREHUS_TIDSLINJEHENDELSER
}