version: '3.4'
services:
  kanvas:
    image: 'kanvas'
    environment:
      VIRTUAL_HOST: kanvas
      SERVICE_PORTS: 8080
      OPEN_AM_ENDPOINT: '[FROM_ENV: OPEN_AM_ENDPOINT]'
      ENVIRONMENT_NAME: '[FROM_ENV: ENVIRONMENT_NAME]'
      ENVIRONMENT_ADDRESS: '[FROM_ENV: ENVIRONMENT_ADDRESS]'
      NODE_ENV: 'prod'
    deploy:
      replicas: 1
      mode: replicated
      resources:
        limits:
          cpus: '0.20'
          memory: 1024m
      update_config:
        order: start-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 30s
    env_file:
      - base-config.env
