name: Bygg og deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/build-app-containerfile.yaml@4bb1015794d4980c090085447975317c11cb7b7a # v1.28.13
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      slack-channel: "#panda-ci"
      slack-bot-name: "GitHub Actions - Kanvas"
      slack-bot-icon: "panda-face"

  deploy:
    needs: build
    uses: statens-pensjonskasse/github-actions-library/.github/workflows/deploy-to-swarm.yaml@4bb1015794d4980c090085447975317c11cb7b7a # v1.28.13
    permissions:
      contents: read
      packages: write
      deployments: write
    secrets: inherit
    with:
      deploy-to-kpt: true
      deploy-to-lyn: true
      deploy-to-prod: true
      branches-to-deploy-to-utv-and-test: 'main, feature/'
      image-tag: ${{ needs.build.outputs.new-image-tag }}
      deployment-config-repo: panda-deployments
      slack-channel: '#panda-cd'
      slack-bot-name: 'Kanvas-CD (Github actions)'
      slack-bot-icon: ':panda_face:'
      reviewers: 'team-reserveberegning'
      ignore-freeze-check: true